import type { AvatarProfile, CityOption, UserPreferences, WardrobeItem } from './types'

export const cityOptions: CityOption[] = [
  {
    city: '上海',
    latitude: 31.2222,
    longitude: 121.4581,
    fallbackWeather: {
      city: '上海',
      temperature: 24,
      feelsLike: 23,
      weatherType: 'cloudy',
      windLevel: 'medium',
      humidity: 66,
      uvLevel: 'high',
      tempGap: 7,
      rainProbability: 25,
    },
  },
  {
    city: '北京',
    latitude: 39.9042,
    longitude: 116.4074,
    fallbackWeather: {
      city: '北京',
      temperature: 28,
      feelsLike: 29,
      weatherType: 'sunny',
      windLevel: 'low',
      humidity: 42,
      uvLevel: 'high',
      tempGap: 9,
      rainProbability: 5,
    },
  },
  {
    city: '广州',
    latitude: 23.1291,
    longitude: 113.2644,
    fallbackWeather: {
      city: '广州',
      temperature: 31,
      feelsLike: 34,
      weatherType: 'rainy',
      windLevel: 'medium',
      humidity: 84,
      uvLevel: 'medium',
      tempGap: 4,
      rainProbability: 72,
    },
  },
]

export const initialPreferences: UserPreferences = {
  preferredStyles: ['commute', 'refined'],
  avoidCategories: [],
  avoidColors: [],
  comfortPriority: 'versatile_first',
  defaultScene: 'commute',
  acceptsLayering: true,
  avoidRepeatLooks: true,
}

export const initialAvatarProfile: AvatarProfile = {
  heightCm: 165,
  weightKg: 55,
  genderPresentation: 'feminine',
  bodyShape: 'balanced',
  shoulderType: 'regular',
  waistType: 'regular',
  hipType: 'regular',
  legLengthType: 'regular',
  tryOnPhotoUrl: null,
}

export const initialWardrobe: WardrobeItem[] = [
  {
    id: 'item-1',
    name: '奶油白衬衫',
    category: 'top',
    colorGroup: 'black_white_gray',
    thickness: 'light',
    style: 'commute',
    status: 'ready',
    seasonFit: 'spring_autumn',
    fitType: 'regular',
    preferenceScore: 82,
    wearCount: 4,
    lastWornAt: '2026-05-10',
    isDisliked: false,
  },
  {
    id: 'item-2',
    name: '烟灰针织短袖',
    category: 'top',
    colorGroup: 'black_white_gray',
    thickness: 'regular',
    style: 'commute',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'slim',
    preferenceScore: 88,
    wearCount: 7,
    lastWornAt: '2026-05-12',
    isDisliked: false,
  },
  {
    id: 'item-3',
    name: '浅蓝牛仔衬衫',
    category: 'top',
    colorGroup: 'denim',
    thickness: 'regular',
    style: 'casual',
    status: 'ready',
    seasonFit: 'spring_autumn',
    fitType: 'relaxed',
    preferenceScore: 70,
    wearCount: 3,
    lastWornAt: '2026-05-08',
    isDisliked: false,
  },
  {
    id: 'item-4',
    name: '雾蓝西装外套',
    category: 'outerwear',
    colorGroup: 'blue',
    thickness: 'regular',
    style: 'commute',
    status: 'ready',
    seasonFit: 'spring_autumn',
    fitType: 'regular',
    preferenceScore: 86,
    wearCount: 5,
    lastWornAt: '2026-05-09',
    isDisliked: false,
  },
  {
    id: 'item-5',
    name: '米杏轻薄开衫',
    category: 'outerwear',
    colorGroup: 'khaki_brown',
    thickness: 'light',
    style: 'refined',
    status: 'ready',
    seasonFit: 'spring_autumn',
    fitType: 'regular',
    preferenceScore: 77,
    wearCount: 6,
    lastWornAt: '2026-05-06',
    isDisliked: false,
  },
  {
    id: 'item-6',
    name: '炭黑直筒西裤',
    category: 'bottom',
    colorGroup: 'black_white_gray',
    thickness: 'regular',
    style: 'commute',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'regular',
    preferenceScore: 91,
    wearCount: 8,
    lastWornAt: '2026-05-11',
    isDisliked: false,
  },
  {
    id: 'item-7',
    name: '燕麦 A 字半裙',
    category: 'bottom',
    colorGroup: 'khaki_brown',
    thickness: 'light',
    style: 'refined',
    status: 'ready',
    seasonFit: 'summer',
    fitType: 'regular',
    preferenceScore: 80,
    wearCount: 2,
    lastWornAt: '2026-05-07',
    isDisliked: false,
  },
  {
    id: 'item-8',
    name: '深蓝锥形牛仔裤',
    category: 'bottom',
    colorGroup: 'denim',
    thickness: 'regular',
    style: 'casual',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'regular',
    preferenceScore: 74,
    wearCount: 5,
    lastWornAt: '2026-05-13',
    isDisliked: false,
  },
  {
    id: 'item-9',
    name: '奶油白连衣裙',
    category: 'dress',
    colorGroup: 'black_white_gray',
    thickness: 'light',
    style: 'refined',
    status: 'ready',
    seasonFit: 'summer',
    fitType: 'regular',
    preferenceScore: 75,
    wearCount: 2,
    lastWornAt: '2026-05-04',
    isDisliked: false,
  },
  {
    id: 'item-10',
    name: '黑色乐福鞋',
    category: 'shoes',
    colorGroup: 'black_white_gray',
    thickness: 'regular',
    style: 'commute',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'regular',
    preferenceScore: 90,
    wearCount: 10,
    lastWornAt: '2026-05-12',
    isDisliked: false,
  },
  {
    id: 'item-11',
    name: '白色简约板鞋',
    category: 'shoes',
    colorGroup: 'black_white_gray',
    thickness: 'light',
    style: 'casual',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'regular',
    preferenceScore: 76,
    wearCount: 9,
    lastWornAt: '2026-05-13',
    isDisliked: false,
  },
  {
    id: 'item-12',
    name: '浅杏低跟单鞋',
    category: 'shoes',
    colorGroup: 'khaki_brown',
    thickness: 'light',
    style: 'refined',
    status: 'ready',
    seasonFit: 'spring_autumn',
    fitType: 'regular',
    preferenceScore: 84,
    wearCount: 4,
    lastWornAt: '2026-05-09',
    isDisliked: false,
  },
  {
    id: 'item-13',
    name: '珍珠短链',
    category: 'accessory',
    colorGroup: 'black_white_gray',
    thickness: 'light',
    style: 'refined',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'slim',
    preferenceScore: 79,
    wearCount: 6,
    lastWornAt: '2026-05-03',
    isDisliked: false,
  },
  {
    id: 'item-14',
    name: '焦糖肩背包',
    category: 'accessory',
    colorGroup: 'khaki_brown',
    thickness: 'regular',
    style: 'commute',
    status: 'ready',
    seasonFit: 'all_season',
    fitType: 'regular',
    preferenceScore: 84,
    wearCount: 8,
    lastWornAt: '2026-05-12',
    isDisliked: false,
  },
]
